polls_test/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path





urlpatterns = [

    
   
    path('', include('polls.urls')), 
    path('admin/', admin.site.urls),
    
   
   
]

polls_test/mysite/polls/urls.py
from django.urls import path

from . import views




app_name = 'polls'
urlpatterns = [
    
   
    path('', views.Home.as_view(), name = 'home'),
    path("accounts/login/", views.LoginView.as_view(), name='register'),
    path("accounts/logout/", views.logout_view, name='log-out'),
    path('main/', views.MainView.as_view(), name='main'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('<int:pk>/results/', views.ResultView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create-poll/', views.CreatePoll.as_view(), name='c-poll'),
    path('<int:pk>/update/', views.PollsUpdate.as_view(), name='update'),
    path('<int:pk>/choice/add/', views.CHOICE.as_view(), name='add_choice'),

    
    path('<int:pk>/delete/', views.PollDeleteView.as_view(), name='deletePoll'),
   
]

polls_test/mysite/polls/models.py
import datetime

from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.utils import timezone



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days = 1) <= self.pub_date <= now
    
    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True, 
        ordering='pub_date', 
        description='Published recently?',

    )
    def was_pulished_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    
    def __str__(self):
        return self.choice_text, self.votes
    

polls_test/mysite/polls/forms.py
from django import forms 
from .models import  Choice, Question

from betterforms.multiform import MultiModelForm
from django.forms import ModelForm



#last_active = forms.DateField(widget=DateInput)

class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'
        widgets = {
            
           'pub_date': forms.DateTimeInput(attrs={'class': 'datepicker'}, format='%Y-%m-%d %H:%M')
        }
       

class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text', 'votes']

class CreatePollform(MultiModelForm):
    class Meta:
        model = Question
        
    choice2 = forms.CharField(label="choice", max_length=100)
    vote2 = forms.IntegerField(label="vote")
    
    form_classes = {
        'question': QuestionForm,
        'choices': ChoiceForm,
        'choices': ChoiceForm,
        'choices2': ChoiceForm,
        'choices3': ChoiceForm,
    }

    
    
   

polls_test/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect 
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_views
from django.contrib import messages
from django.urls import reverse
from django.forms import modelformset_factory
from django.http import JsonResponse

from django.views import generic
from django.views.generic import TemplateView, CreateView, UpdateView,  DeleteView, View
from django.utils import timezone
from django.http import HttpResponseRedirect

from .models import Question, Choice
from .forms import LoginForm, CreatePollform, QuestionForm, ChoiceForm

from django.db import connection


class Home(TemplateView):
    template_name = 'polls/home.html'


class MainView(generic.list.ListView):
    model = Question
    template_name = 'polls/index.html'
    
      
    def get_context_data(self, **kwargs):
        self.object_list = self.get_queryset()
        context = super(MainView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
      #  print(context)
        return context
    
    def get_object(self):
        return Question.objects.all().order_by('-pub_date')

    
    def get(self, request):
        if  not request.user.is_authenticated:
        # messwages.warning(request, 'MENSAJE: Usuario no logeado')
            return redirect(reverse('polls:register'))
        else:
            
            #import pdb; pdb.set_trace()
            context = self.get_context_data()
            return render(request, self.template_name, context)

class DetailView(generic.DetailView):
    #import pdb; pdb.set_trace()   
    model = Question
    template_name = 'polls/detail.html'


    def get_queryset(self):
        
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte = timezone.now())      
   
def vote(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class ResultView(generic.DetailView):
    model =   Question
    template_name = 'polls/results.html'


##  LOGIN VEW   #######

class LoginView(auth_views.LoginView):
    template_name = 'registration/login.html'
    form = LoginForm()

         
    def get(self, request):
        #import pdb; pdb.set_trace()
        if request.method == 'GET':
            form = LoginForm()
            return render(request, self.template_name, {'form': form}) 
        else:
            messages.warning(request, 'no existe formilario') 

        if request.user.is_authenticated:
            return redirect(reverse('polls:main'))
        else: 
            return render(request, self.template_name)   

    def post(self, request):
        form = LoginForm()
        #import pdb; pdb.set_trace()
        username = request.POST['username']
        password = request.POST['password']

        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('polls:main')  #  redirigir a l usuario después de iniciar sesión.
        else:
            # Handle authentication failure (e.g., show an error message)
            messages.error(request, 'La contraseña o el usuario son incorrectos, verifica los datos')
            form = LoginForm()
            return render(request, self.template_name, {'form': form}) 

def logout_view(request):
    logout(request)#toma el request de la pagina con el url asignado y retornar la peticion
    messages.warning(request, 'MENSAJE: El usuario ha cerrado la sesion')
    #redirigiendo al home
    return redirect(reverse('polls:home'))

## ####     CRUD VIEWS          #####

class CreatePoll(CreateView):
    form_class =    CreatePollform
    template_name = 'crud/create_poll.html'
    success_url = reverse_lazy('polls:main')

    def form_valid(self, form):
        pregunta = form['question'].save()
       

        opcion = form['choices'].save(commit=False) 
        opcion2 = form['choices2'].save(commit=False)
        opcion3 = form['choices3'].save(commit = False)
       

        opcion.question = pregunta
        opcion2.question = pregunta
        opcion3.question =  pregunta

        opcion.save()       
        opcion2.save()
        opcion3.save()
        return HttpResponseRedirect(reverse('polls:main'))
        

class PollUpdateQuestionView(UpdateView):
    
    model = Question

    fields = '__all__'
    template_name_suffix = '_update_form'

class CHOICE(View):
    
    model =  Choice
    
    def post(self, request, pk=None):
        
        input_file = self.request.POST.get("inputField") 
        question = Question.objects.get(pk=pk)
        self.model.objects.create(question=question, choice_text=input_file)
        #print(f"este es desde las vistas: {input_file}")

        return JsonResponse({"succes": True, "message":"Registro corretooo!"})
    

    
 

class PollsUpdate(TemplateView):
    
    template_name = 'crud/update_view_update_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pregunta = get_object_or_404(Question,pk=self.kwargs['pk'])
        
        context['question'] = pregunta
        context['quiestion_form'] = QuestionForm(instance=pregunta)

     
        # Crear un modelformset para Choice
        ChoiceFormSet = modelformset_factory(Choice, form=ChoiceForm, extra=0)

        choices = pregunta.choice_set.all()

             
        question_form = QuestionForm(instance=pregunta)
        choice_formset = ChoiceFormSet(queryset=choices)
        

        context['question_form'] = question_form
        context['choice_formset'] = choice_formset

        return context
    
    def post(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        pregunta = get_object_or_404(Question, pk=pk)



        question_form = QuestionForm(instance=pregunta, data=request.POST)
        ChoiceFormSet = modelformset_factory(Choice, form=ChoiceForm, extra=0)
       # import pdb; pdb.set_trace()

        if request.method == 'POST':
            # Procesar el formulario principal
            if question_form.is_valid():
                pregunta = question_form.save()
                choice_formset = ChoiceFormSet(request.POST, queryset=Choice.objects.filter(question=pregunta))
                if choice_formset.is_valid():
                    print("ha entrado en el segundo if")
                else:
                    print("El formset no es válido")
                    print(choice_formset.data)
                    print(choice_formset.errors)



                return HttpResponseRedirect(reverse('polls:main'))  # Asegúrate de definir 'success_page' en tus URLs

        



           
class PollDeleteView(DeleteView):
    model = Question
    template_name = 'crud/delete_view.html'
    success_url = reverse_lazy("polls:main")
   
 

polls_test/mysite/polls/templates/polls/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'polls/detail.css' %}">

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="vote">
    
    </form>
  
    </div>
    <br><a class="btn" href="{% url 'polls:main' %}">Volver a las encuestas</a>
{% endblock %}

polls_test/mysite/polls/templates/polls/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Home {% endblock %}





{% if next %}
    {% if user.is_authenticated %}
   
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}






{% block content %}



  

        <div class="row" style="color:white;">

          <div class="col-sm-4" style="background-color: #131117;">
            <h2>About Me</h2>
            <h5>Pues yo:</h5>
            <img src="static/polls/images/yo.jpg" alt="Una foto de un guapo galan" style="object-fit: cover;">
            <p>Soy Matthewss, y soy un jóven practicante en el área de desarrollo y soporte técnico en finkok y mi meta es tener un gothic gurl tatuada </p>
            <h3 class="mt-4">Some Links</h3>
            <p>Lorem ipsum dolor sit ame.</p>
            <ul class="nav nav-pills flex-column">
              
              <li class="nav-item">
                <p><a class="btn btn-lg" style="background-color:#4C03F1; color: white;" href="{% url 'polls:main' %}" role="button">go to polls &raquo;</a></p>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li>
            </ul>

            <hr class="d-sm-none">
          </div>

          <div class="col-sm-8" style="background-color:050308;">
            <h2 style=" text-decoration: underline overline;">Ejemplo de Proyecto de Encuestas</h2>
            <h5> -Desarrollado en Django</h5>
            <br>
            <p> Los usuarios pueden crear encuestas personalizadas con preguntas de opción múltiple o abiertas. Pueden definir la duración de la encuesta y establecer opciones de privacidad.</p>
            <p>SLos creadores de encuestas pueden ver y administrar todas sus encuestas, incluyendo la posibilidad de editar, eliminar o desactivar encuestas anteriores.</p>
            <p>Los usuarios registrados pueden participar en las encuestas respondiendo a las preguntas proporcionadas. Se pueden proporcionar comentarios o aclaraciones para preguntas abiertas.</p><br>
      
            <h2 class="mt-5">Te Preguntarás donde Hago residencias</h2>
            <h5>Nada más y menos que en FIKOK S.A de C.V</h5>
            <img src="static/polls/images/FKK.png" alt="Una foto de un guapo galan" style="object-fit: cover;"><br>
            <p>¿Quiénes Somos?</p>
            <p>Único proveedor en ofrecer un facturación electrónica OnDemand, es decir, sobre demanda, usted paga solo lo que consume al término del periodo de 30 días. Con FINKOK usted no paga por adelantado, solo pónganse en contacto con nosotros para asignarle a un experto integrador de sistemas, él le ayudara a integrar su sistema con el de FINKOK para comenzar a facturar, esto no tiene ningún costo para usted</p>
          </div>
        </div>
      

 


  

{% endblock %}

polls_test/mysite/polls/templates/polls/index.html
{% extends 'base.html' %}



{% block content %}


    {% if user.is_authenticated %}
   
    {% else %}
   {#No mostrará nada#}
    {% endif %}

    {% if object_list %}
    <ul>
    {% for question in object_list %}
   
<div>
    <div class = "list-group"><br>
    
        <a href="{% url 'polls:detail' question.id  %}" class="list-group-item list-group-item-action flex-column align-items-start active" style="margin-bottom: 10px; background-color:#6920D9; border-style: none;">
            <div class="d-flex w-100 justify-content-between" >
              <h5 class="mb-1">{{ question.question_text }}</h5>
              <small>Publicado el {{question.pub_date}} </p> </small> 
              
                
            </div>
          
          </a>
    </div>
   

    
    <a href="{% url 'polls:update' question.id %}">
        <button type="button" class="btn btn-warning">Update</button>
    </a>
   

    <a href="{% url 'polls:deletePoll' question.id %}">
      <button type="button" class="btn btn-danger">Delete</button>
    </a> 






</div>
    
    {% endfor %}
    </ul>

    {% else %}
    <p>No polls are available.</p>
    {% endif %}

{% endblock content %}


  <h3 style="color:white">  Hi {{ user.username }}  ! </h3>
    
  <p><a class="btn btn-danger btn-lg" href="{% url 'polls:log-out' %}" role="button">Log Out &raquo;</a></p>

polls_test/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

            
<br><a  class="pie" href="{% url 'polls:main' %}">Volver a las encuestas</a>